dist: bionic

language: go

go:
  - 1.16.x

env:
  global:
    - GO111MODULE=on
    - AWS_PROFILE=terradozer
    - AWS_DEFAULT_REGION=us-west-2

before_install:
  - ./aws_credentials.sh

install:
  - make setup

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
notifications:
  email: false